## Tabular Data

In [9]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
distances = np.genfromtxt('distance_data_headers.csv', delimiter=',',dtype='unicode') ### unicode dtype allows strings

In [41]:
headers = distances[0]

['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']


In [11]:
data = distances[1:]

In [17]:
data = data.astype(np.float) ### assigns type to all of the array elements

In [27]:
small_data = data[0:10,0:3]
print(small_data)

[[ 1.      8.9542  5.8024]
 [ 2.      8.6181  6.0942]
 [ 3.      9.0066  6.0637]
 [ 4.      9.2002  6.0227]
 [ 5.      9.1294  5.9365]
 [ 6.      9.0462  6.2553]
 [ 7.      8.8657  5.9186]
 [ 8.      9.3256  6.2351]
 [ 9.      9.4184  6.1993]
 [10.      9.06    6.0478]]


In [31]:
THR4_ATP = np.mean(data[:,1])

In [46]:
avg_distances = []
for i in range(1,5):
    avg_distances.append(np.mean(data[:,i]))
    
print('{}: {}'.format(headers[i], avg_distances[i]))


#bond_bet = ['THR4_ATP', 'THR4_ASP', 'TYR6_ATP', 'TYR6_ASP']
#distances = {}


IndexError: list index out of range